# Generated by Django 3.2.16 on 2023-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_auto_20230306_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
