# Generated by Django 3.2.16 on 2023-01-29 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_auto_20230129_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
