# Generated by Django 3.2.16 on 2023-02-14 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_projectpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='language_icon',
            field=cloudinary.models.CloudinaryField(default='p_language_icon', max_length=255, verbose_name='image'),
        ),
    ]
