# Generated by Django 3.2.16 on 2023-03-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0003_alter_message_sent_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows",
        ),
    ]
