# Generated by Django 3.2.16 on 2023-02-16 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0003_programminglanguage_language_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
