# Generated by Django 3.2.16 on 2023-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='What is the title for your project?', max_length=100, unique=True),
        ),
    ]
