# Generated by Django 3.2.16 on 2023-01-22 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_userprofilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_user',
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, help_text='What is your GitHub username?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, help_text='What is your GitHub URL?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_in',
            field=models.URLField(blank=True, help_text='What is the URL of your linkedin profile?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Where do you live?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.URLField(blank=True, help_text='What is your portfolio URL?', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is the title for your project?', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter your project description here', null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Enter programming language', max_length=50)),
                ('project', models.ManyToManyField(to='app_home.Project')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
