# Generated by Django 3.2.16 on 2023-01-22 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_auto_20230122_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_language',
            field=models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')], default='Python', help_text='Choose your programming language(s)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='project',
            field=models.ManyToManyField(blank=True, to='app_home.Project'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
