# Generated by Django 3.2.16 on 2023-01-22 20:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_auto_20230122_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='p_language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')], help_text='Choose your programming language(s)', max_length=50),
        ),
    ]
